name: simple_dart_showcase_simple
description: showcase using widgets and views
version: 0.1.3
publish_to: none

platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  simple_dart_blue_theme: ^0.0.4
  simple_dart_button: ^0.0.2
  simple_dart_checkbox: ^0.0.3
  simple_dart_context_menu: ^0.0.3
  simple_dart_dark_theme: ^0.0.3
  simple_dart_date_field: ^0.0.3
  simple_dart_default_theme: ^0.0.3
  simple_dart_dialog: ^0.0.2
  simple_dart_dropdown: ^0.0.1
  simple_dart_file_picker: ^0.0.1
  simple_dart_form_panel: ^0.0.1
  simple_dart_headed_panel: ^0.0.2
  simple_dart_image_button: ^0.0.1
  simple_dart_label: ^0.0.1
  simple_dart_link: ^0.0.1
  simple_dart_list_field: ^0.0.3
  simple_dart_load_indicator: ^0.0.1
  simple_dart_loadable_object_table: ^0.0.2
  simple_dart_modal_controller: ^0.0.7
  simple_dart_num_field: ^0.0.3
  simple_dart_object_table: ^0.1.4
  simple_dart_pager: ^0.0.3
  simple_dart_radio_field: ^0.0.2
  simple_dart_select_field: ^0.0.3
  simple_dart_starter_simple: ^0.0.6
  simple_dart_table: ^0.1.2
  simple_dart_tabs_panel: ^0.0.2
  simple_dart_tabs_panel_with_limit: ^0.0.4
  simple_dart_text_area_field: ^0.0.1
  simple_dart_text_field: ^0.0.3
  simple_dart_theme_controller: ^0.0.2
  simple_dart_ui_core: ^0.0.3
  simple_dart_view_controller: ^0.0.1




dev_dependencies:
  build_runner: ^2.3.2
  build_web_compilers:
